title: Haowen Shi
email: harvey.shi@yahoo.com
logo: /assets/img/logo.jpeg
description: >
  Makes Robots
baseurl: ''
url: "https://haowensh.com"
github_username: harveybia
theme: jekyll-theme-minimal
collections:
  projects:
    output: true
x-introduction: >
  Computer engineering and robotics enthusiast.
