title: Haowen Shi
email: haowensh@cs.cmu.edu
logo: /assets/img/logo.jpeg
description: >
  Makes Robots
baseurl: ''
url: "https://haowensh.com"
github_username: harveybia
theme: jekyll-theme-minimal
collections:
  projects:
x-introduction: >
  Master of Science in Robotics (MSR) Student @ Carnegie Mellon
